config/routes.rb
Rails.application.routes.draw do
  root "notes#index"

  resources :notes
  
  # get "notes/new", "notes#new"
  # post "notes/create", "notes#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	has_many :taggings
	has_many :tags, through: :taggings

	def testing_git_flow
		cb="test for conflict with flow"
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :notes, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
	has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  def index
    @user_notes = Note.includes(:tags)
  end

  def new
    user = User.first
    @note = Note.new(user_id: user.id)
  end

  def create
    tags = params[:tags][:ids].reject(&:blank?).map(&:to_i)
    @note = Note.new(note_params.merge(tag_ids: tags))
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def show
    @note = Note.includes(:tags).where('notes.id = ?', params[:id]).first
  end

  def edit
  end

  private

  def note_params
    params.require(:note).permit(:title, :body, :tags, :user_id)
  end

  def params_edit; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
      <div class="modal" tabindex="-1" role="dialog" id="modal-window">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Note detail</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


    </div>

  </body>
</html>

app/views/notes/_note.html.erb
<h1><%=@note.title%></h1>
<p><%=@note.body%></p>
<p><small>Tag: <%= raw @note.tags.map(&:name).join(',') %></small></p>

app/views/notes/index.html.erb
<h1>User Notes</h1>
<% if @user_notes.empty? %>
  <span class="text-warning">There are no tasks!</span>
  <button><a href="<%=new_note_path%>">New Note</a></button>
<% else %>
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Tag</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @user_notes.each do |note| %>
        <tr>
          <td>
            <strong>
              <%= note.title %>
            </strong>
          </td>
          <td class="text-info">
            <%= note.body %>
          </td>
          <td class="text-info">
            <%= note.tags.map(&:name).join(',') %>
          </td>
          <td>
            <%= link_to note_path(note), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' } do %>
              <i>View</i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<a href="<%=new_note_path%>"><button class='btn btn-lg btn-primary'>New Note</button></a>

app/views/notes/new.html.erb
<div class = 'col-md-8 offset-2'>
  <h1 class = "text-center">New Note</h1>
  <%= form_for @note, url: notes_path do |f| %>
    <div class="form-group">
	    <%= f.label :title, "Title:", class: "col-md-4 control-label" %>
	    <div class="col-md-8">
	      <%= f.text_field :title, class: "form-control" %>
	    </div>
	  </div>
	  <div class="form-group">
	    <%= f.label :body, "Body:", class: "col-md-4 control-label" %>
	    <div class="col-md-8">
	      <%= f.text_area :body, class: "form-control" %>
	    </div>
	  </div>

	  <div class="form-group">
	    <%= f.label :tags, "Tags:", class: "col-md-4 control-label" %>
	    <div class="col-md-8">
	    	<%= collection_select(:tags, :ids, Tag.all, :id, :name, {}, {:multiple => true}) %>
	    </div>
	  </div>
	  <%= f.hidden_field :user_id %>
	  <div class="form-group">
    	<%= f.submit "Submit", class: 'btn btn-lg btn-primary float-right' %>
    </div>
  <% end %>
  <button class='btn btn-lg btn-primary'><a href="<%=notes_path%>" style="color: #fff">Back</a></button>
</div>

app/views/notes/show.html.erb
<div class = 'col-md-8 offset-2'>
  <h1><%=@note.title%></h1>
  <p><%=@note.body%></p>
  <p><small>Tag: <%= raw @note.tags.map(&:name).join(',') %></small></p>
</div>

<a href="<%= notes_path%>">Back</a>

app/views/notes/show.js.erb
$(".modal-body").html("<%= escape_javascript(render 'notes/note') %>");